### PR TITLE
Corrections after issue 115

### PR DESCRIPTION
**Pull request by registerrier**
This PR proposes some changes suggested in #115 .

### CODE REVIEW

**Review by adonath — APPROVED** [review]
Thanks @registerrier, no comments from my side.

**Review by adonath — APPROVED** [review]
Thanks @registerrier! No further comments from my side.

**Comment by registerrier** [comment]
The main redundancy I see remaining is the 2.1 and 3.1.
2.1 details the workflow already mentioning the sub-packages and 3.1 gives an overview of the package in the workflow figure.
It could be simplified (e.g. by removing the mention of the sub-packages in section 2)

**Comment by adonath** [comment]
Thanks for double checking @registerrier! I agree that removing the forward references in Section 2.1 is a good solution.

**Pull request merged**
