### PR TITLE
Add codestats figures and table

### PR DESCRIPTION
**Pull request by Bultako**
This PR adds the `src/figure/codestats.py` file which creates the piecharts for the coding languages and extension files present in Gammapy, as well as a LaTex file providing a table with the number statistics for the different types of languages used in the Gammapy project.

### CODE REVIEW

**Comment by adonath** [comment]
Thanks a lot @Bultako, after installing `cloc` locally the code still fails for me with:

```
Traceback (most recent call last):
  File "/Users/adonath/github/adonath/gammapy-v1.0-paper/src/figures/codestats.py", line 133, in <module>
    main()
  File "/Users/adonath/github/adonath/gammapy-v1.0-paper/src/figures/codestats.py", line 126, in main
    make_pie()
  File "/Users/adonath/github/adonath/gammapy-v1.0-paper/src/figures/codestats.py", line 83, in make_pie
    df = df.set_index("Language")
  File "/Users/adonath/github/adonath/gammapy-v1.0-paper/.snakemake/conda/df0a79c5a672950db54ee37a5f7422bd/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/adonath/github/adonath/gammapy-v1.0-paper/.snakemake/conda/df0a79c5a672950db54ee37a5f7422bd/lib/python3.9/site-packages/pandas/core/frame.py", line 5451, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['Language'] are in the columns"
```

**Comment by Bultako** [comment]
@adonath 
I guess you need to add the `gammapy` GitHub repo as a submodule.

https://github.com/gammapy/gammapy-v1.0-paper/blob/325df2d2344c5af84e53b5906e01c7ba4b9eceeb/.gitmodules#L5-L7

**Comment by adonath** [comment]
Thanks @Bultako, just to confirm: a `make clean`, followed by the usual `make` resulted in a successful build. I think the updated piechart, including the docs and test, is exactly what we need! The overall picture it gives makes a good point for the quality of Gammapy: ~35% actual code, ~25% tests, ~40% docs, docstrings and tutorials.

**Review by adonath — APPROVED** [review]
Thanks @Bultako, no further comments from my side...

**Pull request merged**
