### PR TITLE
Add example of multi-instrument analysis: scripts

### PR DESCRIPTION
**Pull request by cosimoNigro**
As an example of multi-instrument analysis combining different data-levels we choose to estimate the Crab Nebula spectrum combining:
- Fermi-LAT observations (reduced with 3D analysis);
- MAGIC observations (reduced with 1D analysis);
- HAWC flux points.

This PR adds the scripts necessary to perform the multi-instrument analysis example.

Will open another PR to add the text for the corresponding section.

### CODE REVIEW

**Comment by cosimoNigro** [comment]
Hello,

I manage to set everything up, down to the figure production. 
In my analysis script (`src/data/multi-instrument/`), though, it seems that the MAGIC data are not taken into account in the fit.
@adonat, @AtreyeeS can you take a look and help me?
The MAGIC flux points are also empty...

Thanks!

**Comment by cosimoNigro** [comment]
Ah, I also changed in the `environment.yml` the installation of `Gammapy`.
Instead of using version 0.19 I am using the dev version in git, otherwise the energy-dependent spectrum reduction will not work.

**Comment by adonath** [comment]
Thanks @cosimoNigro, I'll look into this now...

**Comment by adonath** [comment]
Thanks @cosimoNigro, I added one commit fixing a few little issues with the file declarations in the snake file. I decided to merge the download into a single method as for the plot all data is needed anyway. For the plot I chose an intermediate size now. From a quick look it seems the Magic flux points are all `NaN`, not sure what the issue is there. Locally the build worked, so I'd propose to just merge this PR here and fix the Magic flux points in a follow up PR. Does this sound OK to you?

**Comment by cosimoNigro** [comment]
Thank you @adonath, sure go ahead and merge.

I noticed that, if after fitting I take one of the datasets of MAGIC and do `dataset.plot_fit()` there are no predicted counts.
Might it be that they are even not taken into account even in the multi-instrument fit - maybe something wrong with the safe mask maker?

We can open an issue to solve it if you are satisfied with the setup.

**Pull request merged**
