### PR TITLE
started to fix the multi-instrument analysis

### PR DESCRIPTION
**Pull request by cosimoNigro**
This PR starts to fix the multi-instrument example.

I have isolated the problem. The fit with the MAGIC data fails when a `Models` object composed of a `SkyModel` and a `FovbackgroundModel` (what is read from the `Fermi-LAT-3FHL_models.yaml`) is passed to the fit.
If I pass a simple `SkyModel` with the log parabola, the fit works just fine.

Is there a way to exclude it? 
Will keep working on this.

### CODE REVIEW

**Comment by cosimoNigro** [comment]
Ok, the problem seems to be that when a `SpatialModel` is included in the `Models` used to fit the MAGIC spectral data, the optimization with iminuit does not converge. Here a minimal snippet to reproduce the issue directly starting from OGIP files (that I am attaching). 
```python
import astropy.units as u
from astropy.coordinates import SkyCoord
from gammapy.datasets import SpectrumDatasetOnOff
from gammapy.modeling import Fit
from gammapy.modeling.models import SkyModel, PointSpatialModel, LogParabolaSpectralModel
import matplotlib.pyplot as plt

# load the OGIP files
dataset = SpectrumDatasetOnOff.read("magic_rad_max_stacked_ogip.fits")

# spectral and spatial models
spectral_model = LogParabolaSpectralModel(
    amplitude=1e-12 * u.Unit("cm-2 s-1 TeV-1"),
    alpha=2,
    beta=0.1,
    reference=1 * u.TeV,
)

target_position = SkyCoord(ra=83.63, dec=22.01, unit="deg", frame="icrs")
spatial_model = PointSpatialModel(
    lon_0=target_position.ra,
    lat_0=target_position.dec,
    frame="icrs"
)

# SkyModel with source
model_source = SkyModel(spectral_model=spectral_model, spatial_model=spatial_model, name="crab")
model_source.spatial_model.lon_0.frozen = True
model_source.spatial_model.lat_0.frozen = True

# SkyModel without source
model_no_source = SkyModel(spectral_model=spectral_model, name="Crab")

# fit without source
print("fitting without a source (without a spatial model)")
fit_no_source = Fit()
dataset.models = [model_no_source]
result_no_sourcre = fit_no_source.run(datasets=dataset)

print(result_no_sourcre)
print(dataset.models.parameters.to_table())
print(fit_no_source.minuit)

# now fit with a spatial model source
print("fitting with a source (with a spatial model)")
fit_source = Fit()
dataset.models = [model_source]
result_source = fit_no_source.run(datasets=dataset)

print(result_source)
print(dataset.models.parameters.to_table())
print(fit_source.minuit)
```
[magic_rad_max_stacked_ogip.tar.gz](https://github.com/gammapy/gammapy-v1.0-paper/files/8706642/magic_rad_max_stacked_ogip.tar.gz)

As you will see the second fit will not converge.
Is this a problem with `Gammapy`? @adonath, @registerrier, @QRemy, @AtreyeeS?

Also it is important to note that the multi-instrument analysis with the H.E.S.S. data does not seem to show this error.

**Comment by AtreyeeS** [comment]
Does it make sense physically to have a `spatial_model` for a 1D dataset?

**Comment by adonath** [comment]
Thanks @cosimoNigro for investigating!

> Does it make sense physically to have a spatial_model for a 1D dataset?

Yes, it does! E.g. an extended source might not be fully contained in the analysis region and Gammapy can correct for this using a spatial model. Or an underlying extended source might "leak" into the analysis region. However: if the fit happens to a spectral dataset only the spatial parameters are not constrained. I expect the amplitude and position to be almost 100% correlated. 

In the case of the multi instrument fit the spatial model is constraint by the Fermi data. When computing flux points on the spectral datasets only this is not the case anymore. So before computing the flux points for the spectral datasets one should freeze all the spatial model parameters.

**Comment by cosimoNigro** [comment]
Ok, curiously enough, if I change in the above snippet
```python
dataset = SpectrumDatasetOnOff.read("magic_rad_max_stacked_ogip.fits")
```
with any of the OGIP files in `gammapy-data/joint-crab/spectra` both fit with both models (with and without spatial components) converge...

There is something wrong with the data reduction then, what could be wrong in the OGIPs that prevents a fit with a spatial component (of course with coords frozen) from converging?

**Comment by adonath** [comment]
@cosimoNigro Ah, it is the region definition! 

So if there is a spatial model presenting the model then Gammapy will actually integrate the model over the region definition. However for the energy-dependent rad-max the region is a point region, so the resulting integrated flux is actually zero. We probably need a workaround for this case...

**Comment by adonath** [comment]
One possibility is to maybe split the model definition like:
```
spectral_model = SpectralModel()

model_magic = SkyModel(
    spectral_model=spectral_model,
    name="crab-spectral-only",
    datasets_names=["magic"],
)

model = SkyModel(
    spectral_model=spectral_model,
    spatial_model=SpatiaModel()
    name="crab",
    datasets_names=["fermi", "hawc"],
)
```

**Comment by cosimoNigro** [comment]
Will, by your snippet, the spectral parameters of the two models automatically linked (i.e. will the two LPs be fitted together)?
I will try your workaround.

**Comment by cosimoNigro** [comment]
Hey @adonath, thanks a lot, with your work around we can fit the LP to all the datasets.

The axes labels are still cut though, it's fault of this `fig.add_axes()`, I think. Anyhow
multi_instrument_analysis

Shall I open an issue in `Gammapy` about the issue with the spatial model and the spectral data from observations `RAD_MAX`?

**Comment by adonath** [comment]
Thanks a lot @cosimoNigro, the result looks very good now! 

> Shall I open an issue in Gammapy about the problem with the spatial model and the spectral data obtained from observations with RAD_MAX?

Yes, however I'm not yet 100% what the actual issue is...

**Comment by adonath** [comment]
@cosimoNigro Is this ready to merge from your side?

**Comment by adonath** [comment]
@cosimoNigro You can adjust the numbers in `fig.add_axes()` to contain the labels...

**Comment by adonath** [comment]
@cosimoNigro I'll just go ahead and merge. We can address anything else in follow up PRs.

**Pull request merged**
