### PR TITLE
Write catalog subsection

### PR DESCRIPTION
**Pull request by AtreyeeS**
I can't compile locally - error in codestats in run_cloc
 
```
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cloc'
[Tue Mar  1 16:51:45 2022]
Error in rule codestats:
    jobid: 15
    output: src/tables/generated/codestats.tex
    conda-env: /Users/ASinha/Gammapy-dev/gammapy-v1.0-paper/.snakemake/conda/f04011d7d0581acf890fe3c238008708
    shell:
        cd src/figures/ && python codestats.py
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

any suggestions @Bultako ?

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @AtreyeeS, please install the `cloc` command using one the following methods: https://github.com/AlDanial/cloc#install-via-package-manager

On Mac either `brew` or `port` should work. @bultak I think there is no simple way to integrate `cloc` into the conda environment? Otherwise we could also just commit the tex table to prevent re-running `cloc` every time.

**Comment by registerrier** [comment]
An alternative option would be to use `pygount` which is distributed in the python package index.

**Comment by AtreyeeS** [comment]
Installed `cloc`
Now running into another error

```
Activating conda environment: /Users/ASinha/Gammapy-dev/gammapy-v1.0-paper/.snakemake/conda/f04011d7d0581acf890fe3c238008708
Traceback (most recent call last):
  File "/Users/ASinha/Gammapy-dev/gammapy-v1.0-paper/src/figures/codestats.py", line 162, in <module>
    main()
  File "/Users/ASinha/Gammapy-dev/gammapy-v1.0-paper/src/figures/codestats.py", line 153, in main
    result = run_cloc(args)
  File "/Users/ASinha/Gammapy-dev/gammapy-v1.0-paper/src/figures/codestats.py", line 46, in run_cloc
    PythonAPI  = f"PythonAPI                      {files_api}          {blank_api}          {comment_api}          {code_api}"
UnboundLocalError: local variable 'files_api' referenced before assignment
[Tue Mar  1 18:09:55 2022]
Error in rule codestats:
    jobid: 15
    output: src/tables/generated/codestats.tex
    conda-env: /Users/ASinha/Gammapy-dev/gammapy-v1.0-paper/.snakemake/conda/f04011d7d0581acf890fe3c238008708
    shell:
        cd src/figures/ && python codestats.py
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by Bultako** [comment]
@AtreyeeS 
I guess you do not have `gammapy` folder as a git submodule.
I hope if you do the standard `make clean` and them `make` you will have the environment updated.

**Comment by Bultako** [comment]
@AtreyeeS 
I have a different error when trying to compile this branch locally.
```
active error: text/2-package-subsections/catalog:6: Missing $ inserted
error: halted on potentially-recoverable error as specified
```

This error is solved if underscore in `GAMMAPY_DATA` is escaped in this way `GAMMAPY\_DATA` in the text.

**Comment by AtreyeeS** [comment]
Thank you so much @Bultako for testing this! A `make_clean` and properly including the `\_DATA` solved the issue!

**Review by adonath — APPROVED** [review]
Thanks a lot @AtreyeeS, I have no comments for now...

**Pull request merged**
